### ISSUE TITLE
[ Keyword notification system ] Configure a message broker using `memphis`

### ISSUE THREAD

**Issue by prravda** [prravda/discord-hotdeal-keyword-typescript#5]

**Comment by prravda** [comment]
# Why I choosed memphis?

- lightweight
- easy-to-configure

# Processes

```yaml
services:
  memphis-metadata:
    image: memphisos/memphis-metadata:docker-15.2.0-debian-11-r27
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memphis -p 5005"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - memphis
    ports:
      - '5005:5005'
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
  memphis:
    image: "memphisos/memphis:stable"
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://127.0.0.1:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - ANALYTICS=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  memphis-rest-gateway:
    image: "memphisos/memphis-rest-gateway:latest"
    depends_on:
      memphis:
        condition: service_healthy
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "4444:4444"
    environment:
      - JWT_SECRET=JWT_TEST_PURPOSE
      - REFRESH_JWT_SECRET=REFRESH_JWT_TEST_PURPOSE
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - ROOT_USER=root
      - ROOT_PASSWORD=memphis
      - MEMPHIS_HOST=memphis
      - HTTP_PORT=4444
networks:
  memphis:
    ipam:
      driver: default
```

This is the default `docker-compose.yaml` file described by memphis

```bash
docker compose up
```

Run this containers 



![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/138299a4-f39f-4515-87e7-67a45fef35ba)



After signing in as root with username / password described in compose file, the onboarding processes is showed. I created a station(it is the similar concept of queue of RabbitMQ, topic of Kafka).

 



![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/0e61c9db-4cd6-4dec-a19e-438dc9d87326)




![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/ee731728-e35d-47cf-8a65-2031b097d954)



Then, create app user. 



![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/899a42ac-0825-4a27-ae38-5d09d83dfd4e)



After create an app user, they described the example base code of producer by language/runtime.  

```tsx
import { memphis, Memphis } from 'memphis-dev';

(async function () {
    let memphisConnection: Memphis;

    try {
        memphisConnection = await memphis.connect({
            host: 'localhost',
            username: 'hotdealworker',
            password: 'delta0420'
        });

        const producer = await memphisConnection.producer({
            stationName: 'hotdealupdated',
            producerName: '<producer-name>'
        });

            const headers = memphis.headers()
            headers.add('key', 'value');
            await producer.produce({
                message: Buffer.from("Message: Hello world"), // you can also send JS object - {}
                headers: headers
            });

        memphisConnection.close();
    } catch (ex) {
        console.log(ex);
        if (memphisConnection) memphisConnection.close();
    }
})();
```

And this is example code described in `TypeScript`. 



![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/94dadb16-5607-40f8-b95c-1190697e18ea)



Like producer side, they also provide consumer side example base code. 



![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/2b943b30-f62f-42b1-b135-fffbc30db6eb)
![Image](https://github.com/prravda/discord-hotdeal-node/assets/64535895/df258858-4578-4d0e-825d-16ee616560d2)



Can create a new user so easily!
